app/authentication/routes.py
import os
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash
)
from flask_login import login_user, logout_user, login_required
from model.user_service import UserService

auth = Blueprint("auth", __name__, url_prefix="/rp/tester/auth")
auth.template_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template/')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = UserService.login(username, password)
        if(user is not None):
            login_user(user)
            return redirect(url_for('auth.account'))
        else:
            flash('Login failed! Please check your username and password.')
    users = UserService.get_users()
    return render_template('login.html', rp_users = users)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/account', methods=['GET'])
@login_required
def account():
    return render_template('account.html')

app/main/routes.py
import os
from flask import (Blueprint, render_template)
from app_config.config import ConfService as cfgserv

base = Blueprint("index", __name__, url_prefix="/rp")
base.template_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template/')

@base.route('/', methods=['GET'])
def index():
    route_url=cfgserv.service_url+"/tester"
    return render_template('index.html', redirect_url=route_url)

app/model/main/routes.py
# coding: latin-1
###############################################################################
# Copyright 2025 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

import os
from flask import (Blueprint, render_template)
from app_config.config import ConfigClass as Config

base = Blueprint("index", __name__, url_prefix="/rp")
base.template_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template/')

@base.route('/', methods=['GET'])
def index():
    route_url= Config.service_url + "/tester"
    return render_template('index.html', redirect_url=route_url)

app/routes.py
# coding: latin-1
###############################################################################
# Copyright 2025 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

import os, base64, qrcode, io, mimetypes, time
from flask import (
    Blueprint, render_template, request, session, send_from_directory, current_app as app, Response, jsonify
)
from flask_login import login_required
from app_config.config import ConfigClass as Config
import model.wallet.requests as wallet_interaction
import model.wallet.db as db

rp = Blueprint("RP", __name__, url_prefix="/rp/tester")
rp.template_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template/')

route_url = Config.service_url + "/tester"

@rp.route('/', methods=['GET'])
def main():
    return render_template('welcome-page.html')

# Display pages where the documents to sign can be chosen
@rp.route('/document/select', methods=['GET'])
@login_required
def select_document():
    remove_session_values(variable_name="form_global")
    return render_template('select-document-page.html')

# Loads the selected documents and display the page to choose the signature options
@rp.route('/document/options', methods=['POST'])
@login_required
def check():
    document_type_chosen = request.form["items"]
    app.logger.info(f"Document Types Selected: {document_type_chosen}.")

    documents_chosen = []
    signature_format = []
    if 'pdf' in document_type_chosen:
        documents_chosen.append('sample.pdf')
        signature_format.append('PAdES')
    if 'json' in document_type_chosen:
        documents_chosen.append('sample.json')
        signature_format.append('JAdES')
    if 'txt' in document_type_chosen:
        documents_chosen.append('sample.txt')
        signature_format.append('CAdES')
    if 'xml' in document_type_chosen:
        documents_chosen.append('sample.xml')
        signature_format.append('XAdES')
    if 'pdf' not in document_type_chosen and 'json' not in document_type_chosen and 'txt' not in document_type_chosen and 'xml' not in document_type_chosen:
        app.logger.error("The document type selected is not supported.")
        return render_template('500.html', error="One of the types selected is not supported.")
    app.logger.info("Retrieved the files: "+ str(documents_chosen))

    hash_algos = [{"name":"SHA256", "oid":"2.16.840.1.101.3.4.2.1"}]
    app.logger.info("Displaying the signature options page.")
    return render_template('select-options-page.html', list_docs=list(zip(documents_chosen, signature_format)), digest_algorithms=hash_algos)

# Retrieve document with given name
@rp.route('/document/<path:filename>', methods=['GET'])
def serve_docs(filename):
    app.logger.info("Requested the file: "+ filename)
    return send_from_directory('docs', filename)

@rp.route("/document/sign", methods=['POST'])
@login_required
def sca_signature_flow():
    form = request.form
    app.logger.info("Received a form with signing options for the document "+form.get("filename"))

    form_global = session.get("form_global")
    if form_global is None:
        form_global = [form]
        update_session_values(variable_name="form_global", variable_value=form_global)
    else:
        form_global.append(form)
        update_session_values(variable_name="form_global", variable_value=form_global)

    app.logger.info("Successfully saved the signature options chosen.")
    return Response("Ok", 200)

@rp.route("/document/sign", methods=['GET'])
@login_required
def sca_signature_page():
    return render_template('select-wallet-page.html')

def get_document_content(filename):
    # Construct the path to the file in the "docs" folder
    file_path = os.path.join(Config.LOAD_FOLDER, filename)

    # Check if the file exists before trying to read it
    if not os.path.isfile(file_path):
        return f"File '{filename}' not found in the docs directory", 404

    # Read the content of the file to encode it in base64
    with open(file_path, 'rb') as document:
        document_content = document.read()
    return document_content

def start_wallet_interaction(wallet_url, scheme):
    list_forms = session.get("form_global")
    if list_forms is None:
        app.logger.error("The signature options information is missing.")
        render_template("500.html", error="The signature settings are missing.")
    app.logger.info("Retrieved signature options forms.")

    documents_info = []
    documents_url = []
    hash_algorithm_oid = None
    for form in list_forms:
        filename = form.get("filename")
        hash_algorithm_oid = form.get("digest_algorithm")
        if filename is None:
            app.logger.error("The filename is missing.")
            render_template("500.html", error="One of the filenames is missing.")
        app.logger.info(f"Retrieve signature options for document: {filename} with hash algorithm: {hash_algorithm_oid}")

        document_content = get_document_content(filename)
        documents_info.append({"filename": filename, "document_content": document_content})
        app.logger.info("Retrieved document content for file: "+filename)

        document_url = route_url+"/document/"+filename
        documents_url.append(document_url)
        app.logger.info(f"Retrieved document url: {documents_url} for file: {filename}")

    link_to_wallet_tester, nonce = wallet_interaction.sd_retrieval_from_authorization_request(
        documents_info=documents_info,
        documents_url=documents_url,
        hash_algorithm_oid=hash_algorithm_oid,
        wallet_url=wallet_url,
        client_id_scheme = scheme
    )    
    app.logger.info(f"Retrieved link to Wallet: {link_to_wallet_tester} with nonce: {nonce}")
    
    retrieve_signed_document_url = route_url+"/document/signed?nonce="+nonce
    app.logger.info(f"URL where to retrieve signed document: {retrieve_signed_document_url}")
    
    # Render HTML page with QrCode
    qr_img = qrcode.make(link_to_wallet_tester)
    buffer = io.BytesIO()
    qr_img.save(buffer, format='PNG')
    buffer.seek(0)
    qr_img_base64 = "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode("utf-8")
    app.logger.info("Obtained QrCode Image.")
    return render_template('redirect-wallet-page.html', url=link_to_wallet_tester, qrcode=qr_img_base64, retrieve_signed_document_url=retrieve_signed_document_url)

# Sign with Wallet Tester for development purposes
@rp.route("/document/sign/tester", methods=['GET'])
@login_required
def sign_with_wallet_tester():
    client_id_scheme = request.args.get("scheme")
    if client_id_scheme != "pre-registered" and client_id_scheme != "x509_san_dns":
        return render_template("500.html")
    app.logger.info("Client Id Scheme: "+client_id_scheme)

    wallet_url = Config.wallet_url
    return start_wallet_interaction(wallet_url, client_id_scheme)

# Sign with Wallet with scheme "mdoc-openid4vp://"
@rp.route("/document/sign/wallet", methods=['GET'])
@login_required
def sign_with_wallet():
    client_id_scheme = request.args.get("scheme")
    if client_id_scheme != "pre-registered" and client_id_scheme != "x509_san_dns":
        return render_template("500.html")
    app.logger.info("Client Id Scheme: " + client_id_scheme)

    wallet_url = "mdoc-openid4vp://" + Config.service_domain
    return start_wallet_interaction(wallet_url, client_id_scheme)

# Display with Wallet with scheme "eudi-rqes://"
@rp.route("/document/sign/wallet/reference-implementation", methods=['GET'])
@login_required
def sign_with_reference_implementation():
    client_id_scheme = request.args.get("scheme")
    if client_id_scheme != "pre-registered" and client_id_scheme != "x509_san_dns":
        return render_template("500.html")
    app.logger.info("Client Id Scheme: " + client_id_scheme)

    wallet_url = "eudi-rqes://" + Config.service_domain
    return start_wallet_interaction(wallet_url, client_id_scheme)

# Waiting for signed document from Wallet
@rp.route("/document/signed", methods=['GET'])
@login_required
def wait_for_signed_document():
    nonce = request.args.get('nonce')
    app.logger.info(f"Retrieve signed document associated to the nonce: {nonce}")
    timeout = time.time() + 60*10 # 10 minutes
    
    signed_document = None
    found = False 
    while not found and time.time() < timeout:
        response = wallet_interaction.retrieve_signed_objects(nonce=nonce)
        if response is not None:
            found = True
            signed_document = response
            app.logger.info(f"Retrieved signed document.")
        else:
            app.logger.info("Signed document not received yet. Waiting for signed document...")
            time.sleep(15)
    
    if not found:
        app.logger.error("Relying Party Tester timed out while waiting for the signed document from the Wallet.")
        db.remove_request_object_with_request_id(nonce)
        remove_session_values("form_global")
        return Response("Relying Party Tester timed out while waiting for the signed document from the Wallet.", status=408)
    else:
        app.logger.info("Successfully received signed document from Wallet.")
        form_list = session.get("form_global")
        data = []
        for form, doc in zip(form_list, signed_document):
            filename = form.get("filename")
            app.logger.info(f"Found the filename to sign {filename} and the expected signed document.")

app/templates/account-page.html
<!--
Copyright 2025 European Commission

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

{% extends 'base.html' %} {% block content %}
<div class="container-fluid h-100">
  <div class="content-box col-md-11 mx-auto text-center">
    <h2>EUDI Wallet</h2>
    <h1>Relying Party Tester</h1>
    <div class="genericErrors" id="genericErrorsDesc"></div>
  
    <a class="btn custom-btn" type="submit" href="{{ url_for('RP.select_document') }}">Sign Document</a>
    <a class="btn custom-btn" type="submit" href="{{ url_for('auth.logout') }}">Logout</a>
      
  </div>
</div>
{% endblock %}

app/templates/account.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid h-100">
  <div class="content-box col-md-11 mx-auto text-center">
    <div class="main-page-box">
      <h3>EUDI Wallet</h2>
      <h1>Relying Party Tester</h1>
      <div class="genericErrors" id="genericErrorsDesc"></div>
  
      <a class="btn custom-btn" type="submit" href="{{ url_for('RP.select_document') }}">Sign Document</a>
      <a class="btn custom-btn" type="submit" href="{{ url_for('auth.logout') }}">Logout</a>
      
    </div>
  </div>
</div>
{% endblock %}

app/templates/base.html
<!--
Copyright 2025 European Commission

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
    />
    <meta name="theme-color" content="#000000" />
    <meta name="Title" content="rQES Relying Party" />
    <meta name="robots" content="noindex, nofollow" />
    <meta
      http-equiv="Cache-Control"
      content="no-cache,no-store,must-revalidate"
    />
    <meta http-equiv="Pragma" content="no-cache" />

    <link
      rel="icon"
      href="{{ url_for('static', filename='images/favicon.gif') }}"
      type="image/gif"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/stylesheets/custom/custom_en_9.7.1.20.1679559965505.css') }}"
      media="all"
      type="text/css"
    />
    <script
      type="text/javascript"
      id="jqueryId"
      src="{{ url_for('static', filename='scripts/jquery/jquery-3.6.3.min.js') }}"
      charset="UTF-8"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='scripts/promiz/promiz-1.0.6.js') }}"
      charset="UTF-8"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='scripts/html5shiv/html5shiv-3.7.3.js') }}"
      charset="UTF-8"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='scripts/respond/respond-1.4.2.js') }}"
      charset="UTF-8"
    ></script>
    <meta name="referrer" content="no-referrer" />
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='scripts/loc/loc_en_9.7.1.20.1679559965505.js') }}"
      charset="UTF-8"
    ></script>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

    <!--Personalized CSS-->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='personalized.css') }}"
      media="all"
      type="text/css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <title>rQES Relying Party</title>
  </head>

  <body id="responsive-main-nav1">
    <div class="main">
      <header role="banner" class="main-header shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid" id="header-container">
            <div>
              <a class="navbar-brand col-md-9" href="#">
                <img
                  src="{{ url_for('static', filename='ic-logo.svg') }}"
                  alt="Logo"
                  height="45"
                />
              </a>
            </div>

            <!-- Navbar Toggle (for mobile) -->
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNav"
            >
              <span class="navbar-toggler-icon"></span>
            </button>

            <div
              class="collapse navbar-collapse justify-content-end"
              id="navbarNav"
            >
              <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a
                    class="nav-link btn btn-primary px-3"
                    href="{{ url_for('auth.account') }}"
                    >Home</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    class="nav-link btn btn-primary px-3"
                    href="{{ url_for('auth.logout') }}"
                    >Logout</a
                  >
                </li>
                {% else %}
                <li class="nav-item">
                  <a
                    class="nav-link btn btn-primary px-3"
                    href="{{ url_for('auth.login') }}"
                    >Login</a
                  >
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <div role="main" class="container">
        {% block content %} {% endblock %}
      </div>

      <footer id="main-footer">
        <div class="container-fluid">
          <div class="row text-center text-md-start align-items-center">
            <div
              class="col-12 col-md-3 mb-3 mb-md-0 text-md-start col-md-3 footer-column"
            >
              <a
                href="https://ec.europa.eu/digital-building-blocks/sites/display/EUDIGITALIDENTITYWALLET/EU+Digital+Identity+Wallet+Home"
                target="_blank"
                ><img
                  src="{{ url_for('static', filename='images/ic-logo.svg') }}"
                  alt="Logo"
                  height="45"
              /></a>
              <small class="d-block mt-2"
                >2025.01.14-Demo (release 0.2.0)</small
              >
            </div>
            <div class="col-12 col-md-3 mb-2 mb-md-0 footer-column">
              <a
                class="d-block footer-column-a"
                href="https://ec.europa.eu/digital-building-blocks/sites/display/EUDIGITALIDENTITYWALLET/EU+Digital+Identity+Wallet+Home"
                target="_blank"
                >About Us</a
              >
            </div>
            <div class="col-12 col-md-3 mb-2 mb-md-0 footer-column">
              <a
                class="d-block footer-column-a"
                href="mailto:CNECT-EUDIW-SUPPORT@ec.europa.eu"
                >Contact Us</a
              >
            </div>
            <div class="col-12 col-md-3 footer-column">
              <a
                class="d-block footer-column-a"
                href="pdf/EU Digital Identity Wallet website_privacy statement.pdf"
                target="_blank"
                >Privacy Statement</a
              >
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/templates/choose_wallet.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid h-100">
  <div class="content-box col-md-11 mx-auto text-center">
    <!-- Error message display -->
    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul class="error-message">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}

    <h1>Sign Document</h1>
    <h2>Sign with Wallet</h2>

    <div class="btn custom-btn">
      <a
        href="{{ url_for('RP.sign_with_wallet') }}"
        style="color: white; text-decoration: none"
        >Test with EUDI Wallet</a
      >
    </div>
    <div class="btn custom-btn">
      <a
        href="{{ url_for('RP.sign_with_wallet_tester') }}"
        style="color: white; text-decoration: none"
        >Test with Wallet Tester</a
      >
    </div>
  </div>
</div>
{% endblock %}

app/templates/select-options-page.html
<!--
Copyright 2025 European Commission

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

{% extends 'base.html' %} {% block content %}
<div class="container-fluid h-100">
  <div class="content-box col-md-11 mx-auto text-center">
    <h1>Sign Document</h1>
    <h2>Select Signature Options</h2>

    <div class="genericErrors" id="genericErrorsDesc"></div>

    <div id="toast" class="toast">Form submitted successfully!</div>

    {% for filename, signature_format in list_docs %} {%
    include 'single-option-file-page.html' %} {% endfor %}

    <div hidden="true" id="sent-options"></div>

    <button class="btn custom-btn" onclick="onClick()">Continue</button>
  </div>
</div>
<script>
  let submittedForms = {}; // Track form submissions

  // Function to mark a form as submitted
  function markFormSubmitted(filename) {
    console.log(filename);
    submittedForms[filename] = true;
    console.log(`Form for ${filename} submitted`);
  }

  function showToast(message) {
    let toast = document.getElementById("toast");
    toast.textContent = message;
    toast.classList.add("show");

    setTimeout(() => {
        toast.classList.add("hide");
        setTimeout(() => {
            toast.classList.remove("show", "hide");
        }, 500); // Wait for fade-out transition
    }, 3000);
  }

  var docs = {{ list_docs | tojson }};
  console.log(docs);

  function onClick(){
    let docs_size = docs.length;
    console.log(docs_size);
    let allForms = document.querySelectorAll("form");
    let totalForms = allForms.length;
    console.log(totalForms);
    let submittedCount = Object.keys(submittedForms).length;
    console.log(submittedCount);

    if (submittedCount === totalForms) {
      window.location.href = "{{ url_for('RP.sca_signature_page') }}";
    } else {
      showToast(`You need to submit all forms before continuing! (${submittedCount}/${totalForms} submitted)`);
    }
  }

</script>
{% endblock %}

app/templates/select_options.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid h-100">
  <div class="content-box col-md-11 mx-auto text-center">
    <h1>Sign Document</h1>
    <h2>Select Signature Options</h2>

    <div class="genericErrors" id="genericErrorsDesc"></div>

    <div class="preview-area" id="previewArea">
      <h3>Chosen Document: {{ filename }}</h3>
      <div class="preview-document" style="padding-top: 56.25%">
        <iframe
          class="responsive-iframe"
          src="/rp/tester/document/{{ filename }}"
          title="Document to Sign"
        ></iframe>
      </div>
    </div>

    <div class="options-form">
      <form action="{{ url_for('RP.sca_signature_flow') }}" method="post">
        <input type="hidden" name="filename" value="{{ filename }}" />

        <!--Signature Format-->
        <div class="options-form-group">
          <label>
            <input
              type="hidden"
              name="signature_format"
              value="{{ signature_format }}"
            />
            <strong style="color: #0048d2; font-size: 14px"
              >Signature Format:</strong
            >
            {{ signature_format }}
          </label>
        </div>

        <!--Container-->
        {% if signature_format in ['XAdES', 'CAdES'] %}
        <div class="options-form-group">
          <legend>Select the container:</legend>
          <label>
            <input
              type="radio"
              id="no"
              name="container"
              value="No"
              onchange="updatePackagingOptions(this.value)"
              checked
            />
            No
          </label>
          <label>
            <input
              type="radio"
              id="asic-s"
              name="container"
              value="ASiC-S"
              onchange="updatePackagingOptions(this.value)"
            />
            ASiC-S
          </label>

          <label>
            <input
              type="radio"
              id="asic-e"
              name="container"
              value="ASiC-E"
              onchange="updatePackagingOptions(this.value)"
            />
            ASiC-E
          </label>
        </div>
        {% else %}
        <div class="options-form-group">
          <legend>Select the container:</legend>

          <label>
            <input
              type="radio"
              id="no"
              name="container"
              value="No"
              onchange="updatePackagingOptions(this.value)"
              checked
            />
            No
          </label>
        </div>
        {% endif %}

        <!--Packaging-->
        <div class="options-form-group" id="packaging-options">
          <legend>Select the packaging:</legend>

          {% if signature_format in ['PAdES', 'XAdES'] %}
          <label>
            <input type="radio" name="packaging" value="ENVELOPED" checked />
            Enveloped
          </label>
          {% endif %} {% if signature_format in ['XAdES', 'CAdES', 'JAdES'] %}
          <label>
            <input type="radio" name="packaging" value="ENVELOPING" />
            Enveloping
          </label>
          <label>
            <input type="radio" name="packaging" value="DETACHED" />
            Detached
          </label>
          {% endif %} {% if signature_format == 'XAdES' %}
          <label>
            <input type="radio" name="packaging" value="INTERNALLY_DETACHED" />
            Internally Detached
          </label>
          {% endif %}
        </div>

        <!--Level-->
        <div class="options-form-group">
          <legend>Select the level:</legend>

          <label>
            <input type="radio" name="level" value="Ades-B-B" checked />
            BASELINE-B
          </label>
          <label>
            <input type="radio" name="level" value="Ades-B-T" />
            BASELINE-T
          </label>
          <label>
            <input type="radio" name="level" value="Ades-B-LT" />
            BASELINE-LT
          </label>
          <label>
            <input type="radio" name="level" value="Ades-B-LTA" />
            BASELINE-LTA
          </label>
        </div>

        <!--Digest Algorithm-->
        <div class="options-form-group">
          <legend>Select the digest algorithm:</legend>

          {% for algorithm in digest_algorithms %}
          <label>
            <input
              type="radio"
              name="digest_algorithm"
              value="{{ algorithm.oid }}"
              {%
              if
              loop.first
              %}checked{%
              endif
              %}
            />
            {{ algorithm.name }}
          </label>
          {% endfor %}
        </div>

        <div class="button-container">
          <button type="submit" class="btn custom-btn">Continue</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  function updatePackagingOptions(new_value) {
    const container = new_value;
    const packagingDiv = document.getElementById("packaging-options");
    let signatureFormat = "{{ signature_format }}";
    let packagingHtml = "";

    if (
      (container === "ASiC-S" || container === "ASiC-E") &&
      (signatureFormat === "XAdES" || signatureFormat === "CAdES")
    ) {
      packagingHtml +=
        '<label><input type="radio" name="packaging" value="DETACHED" checked/>Detached</label>';
    } else {
      switch (signatureFormat) {
        case "PAdES":
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="ENVELOPED" checked/> Enveloped</label>';
          break;
        case "XAdES":
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="ENVELOPED" checked/> Enveloped</label>';
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="ENVELOPING"/> Enveloping</label>';
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="DETACHED"/> Detached</label>';
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="INTERNALLY_DETACHED"/>Internally Detached</label>';
          break;
        case "CAdES":
        case "JAdES":
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="ENVELOPING"/> Enveloping</label>';
          packagingHtml +=
            '<label><input type="radio" name="packaging" value="DETACHED"/> Detached</label>';
          break;
      }
    }

    packagingDiv.innerHTML =
      `<legend>Select the packaging:</legend>` + packagingHtml;
  }
</script>

{% endblock %}